build:
	gcc -Wall ./src/*.c -I /Users/sebsiv/Development/SDL_t_rasterizer/sdl-rasterizer-main/"SDL2 files"/SDL2 -L /Users/sebsiv/Development/SDL_t_rasterizer/sdl-rasterizer-main/"SDL2 files"/lib -l SDL2-2.0.0 -o tr_rasterizer

run:
	./tr_rasterizer

clean:
	rm tr_rasterizer









# makefile if SDL2 is not inside project
# build: \
	gcc -Wall ./src/*.c -I /opt/homebrew/Cellar/sdl2/2.30.1/include/SDL2 -L  /opt/homebrew/Cellar/sdl2/2.30.1/lib -l SDL2-2.0.0 -o rasterizer 

# run: \
	./rasterizer 

# clean: \
	rm rasterizer 
